## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmwg?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialSize: 5

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

#java文件重新编译
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: web/src/main/java/com/xmwg/wq #设置重启的目录

  thymeleaf:
    cache: false # Enable template caching.
    check-template-location: true  # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
#  mvc:
#    view:
#      prefix: /WEB-INF/jsps/ #指定mvc视图的前缀.
#      suffix: .jsp #指定mvc视图的后缀.


#日志
logging:
  level.root: info
  level.com.xmwg.wq: debug
  level.org.hibernate.SQL: debug
  path: logs/
  file: core.log
